### ISSUE TITLE
CRM 2016 Get-XrmSolution : Metadata contains a reference that cannot be resolved 

### ISSUE THREAD

**Issue by bradsymons** [WaelHamze/xrm-ci-framework#1]
Hi Wael

We use your framework for all our CRM automation tasks. We are currently upgrading to CRM 2016 and have hit an issue with some of our environments.
We have 5 environments, DEV, INT, QA, STRESS, PROD.
DEV, QA and PROD were originally 2013 Installs and have been upgraded to 2015 and now 2016. the XrmCi Framework works perfectly on these, (we haven't done prod yet). Even your old 2013 version from codeplex works.
INT an Stress only ever had CRM 2015 on them and have now been upgraded to 2016. When we try do any of the commands we get the following error.

> "Metadata contains a reference that cannot be resolved: 'https://crmstr.XXXXXX.co.za/ORGNAME/XRMServices/2011/Organization.svc?wsdl=wsdl0'. ---> System.InvalidOperationException: There is an error in XML document (1, 1253). ---> System.Xml.XmlException: The maximum nametable character count quota (16384) has been exceeded while reading XML data. The nametable is a data structure used to store strings encountered during XML processing - long XML documents with non-repeating element names, attribute names and attribute values may trigger this quota. This quota may be increased by changing the MaxNameTableCharCount property on the XmlDictionaryReaderQuotas object used when creating the XML reader."

I have tried taking your source from here and updating the packages to the latest 8.0.2.1 SDK versions and the error still persists. 
I have also tried writing a simple console application and copying the code from the GetXrmSolutionCommand.cs file and used the 8.0.2.1 references and this works 100% fine on all environments.

Have you seen this yourself at all?

**Comment by ikurtev** [comment]
Brad,

Just like you, I have used the XRMCIFramework for over a year now, initially with CRM 2015 Online and currently with CRM 2016 Online. For this purpose, I have upgraded the framework to use the latest SDK DLL's. I just want to confirm that when you did that, you upgraded the XrmCommandBase class to use the CrmServiceClient class instead of CrmConnection, which is now internal. For your reference, here are the changes that I have made to this class:
![image](https://cloud.githubusercontent.com/assets/16546265/14497102/aa087f7c-0163-11e6-981c-f1e6b92a1843.png)

The reason I'm bringing this up is that the error above is what appears to be a connection issue with CRM. If you're using CRM On Premise, it could also be due to an IFD issue. But to know for certain, it is best to upgrade to the latest SDK and eliminate that as a possibility.

Ivan

**Comment by bradsymons** [comment]
Hi Ivan, thanks we actually just tried this today after some more investigations and have got it working.

**Comment by WaelHamze** [comment]
I have just updated the Framework for CRM 365 and also included some VSTS tasks.

**Comment by ikurtev** [comment]
Way to go, Wael! I had updated the framework to use the CRM 2016 SDK and have been using a lot lately with VSTS. I even figured out how to include the Package Deployer log file in the build artifacts which is helpful sometimes. I have been using the generic PowerShell step and calling the scripts in the toolkit directly but it looks like you introducing custom build steps, which is very neat. I've also been diving recently into the Release feature in TFS to separate the build vs deployment and to deploy the artifacts of a build to multiple environment with the appropriate approvals and checks. The only difference is that PowerShell folder needs to be included as an artifact and then invoked from a Release step. Overall, releases add some very nice capabilities.

**Comment by WaelHamze** [comment]
Nice to see you are using the framework and the source code has been helpful.
Yes with the tasks I am trying to make it as easy as possible to create automated builds and releases. Obviously PowerShell gives you the most flexibility.

With regards to PackageDeployer, I noticed the logs files are not created each time and they get appended too. Do you delete the existing logs at the start so you only have logs relating to current execution or you take all the history?

**Comment by ikurtev** [comment]
Wael, yes, the log file does not get cleared, but having it available still helps. I guess if you wanted to you could issue a command to delete the file after it is copied to build artifacts, but it has never bothered me as long as I can get the information I need. I have tried copying it to build artifacts from a release, but that doesn't work so well since releases do not generate build artifacts. I am still trying to figure out how to get it from a release. Given how easy it is to set a local build agent, it may make sense to go down that path instead. One recommendation: add a -Verbose switch to the call to Get-CrmConnection on lines 50-51 in DeployPackage.ps1. I found this out after working closely with someone at Microsoft. Passing a -Verbose switch to Import-CrmPackage does not work as expected, the switch needs to be passed to Get-CrmConnection.  Overall, I cannot thank you for putting this framework together!
