### ISSUE TITLE
Deploy plugins from source?

### ISSUE THREAD

**Issue by tklooster** [WaelHamze/xrm-ci-framework#16]
Wael,

We use your 2013 version framework and really appreciate your continued work on this invaluable tool.  My question is how can we deploy plugins to an org from source like the 2013 version?  We use the dev toolkit CRMPackage project with a register file for the plugins/workflows/etc.  I'm testing your 365 version on TFS 2017.

**Comment by ikurtev** [comment]
@tklooster - first, you need to use the solution packager with a mapping file. The mapping file should have an instruction to map your plugin DLL. When you check in your solution, the DLL file will get skipped from the unpacked files. Second, you need to have a task in your Build definition that compiles the Visual Studio solution that contains your plug-in source. In general, I recommend starting with the Visual Studio build template and adding a solution pack step from the XRM CI Framework. Either way, when packing, your mapping file should point to the location where your plugins are compiled on the Build server. This part is tricky and depends on the structure of your source.  If you set the system.debug variable of your Build to true and run the build, you should be able to see the path where you plugin DLL is placed on the Build Server and you can tweak your mapping file. Here is an instruction in a mapping file that you use:  <FileToFile map="MyPluginName.dll" to="..\..\MySolutionName.MyPluginProjectname\bin\Release\MyPluginName.dll" />. This would work if your solution files folder is one level deeper than  your Visual Studio solution. Otherwise, as I said, you need to monitor the output of the build and figure out how to make the path work. Hope this helps. Check the solution packager documentation in the SDK for more info on using a mapping file.  Lastly, you can use a similar approach to pack latest JScript web resources as well without the need to compile anything, but the idea is still that you are deploying code components from source, not from what is in the Dev environment where you exported the solution from.

**Comment by tklooster** [comment]
Thanks Wael, the Solution Packager was the missing piece I hadn't considered.  This looks doable.  I'll report back after I try it.

**Comment by WaelHamze** [comment]
The solution packager would be the way to do as @ikurtev suggested.

**Comment by tklooster** [comment]
Sorry @ikurtev! I didn't look at the name on the response.  Yes, your solution was correct and much appreciated!

**Comment by tklooster** [comment]
Issue is a little old but we're revisiting it since moving to Azure Pipelines.  I can map the plugin assembly and deploy it but how do you deploy the plugin steps and images if you use a .crmregister file?  I can unpack the solution and see the SdkMessageProcessingSteps and deploy those but then we're not using our reg file.  Thanks.
