### ISSUE TITLE
Export solution cmdlet onpremise gives "WARNING: Unable to Login to Dynamics CRM"

### ISSUE THREAD

**Issue by scubaracer** [WaelHamze/xrm-ci-framework#196]
Hi, with version 9.0.0.33 of the XrmCIFramework cmdlet i get "WARNING: Unable to Login to Dynamics CRM" when trying to export a solution. With version .31 i don't have any problems.

**Comment by WaelHamze** [comment]
@scubaracer the update comes with 9.0.2.11 of the tooling library: https://www.nuget.org/packages/Microsoft.CrmSdk.XrmTooling.CoreAssembly/

There has been some minor changes since 9.0.2.5. I suggest having a look at the docs to see if you can spot any difference that may impact you.

You can carry on using .31 as a backup for now.

**Comment by scubaracer** [comment]
We had some issues before with the tooling connector (9.0.2.7) when trying to connect to environments. Like casting exceptions from genereated code by the svcutil.

**Comment by nikitaus** [comment]
@WaelHamze hi, I have the same issue for Dynamics 365 8.2.2.112. Do you have ideas about how to fix that?

**Comment by WaelHamze** [comment]
@scubaracer @nikitaus this should work now with latest nuget package
