### ISSUE TITLE
Issue with Dynamic value in "Set Version" task (Visual Studio Online)

### ISSUE THREAD

**Issue by namurdock** [WaelHamze/xrm-ci-framework#21]
I am trying to use the update version task but I getting the following error:
 
> 2017-05-03T20:14:53.9206240Z ==============================================================================
> 2017-05-03T20:14:53.9206240Z Task         : MSCRM Set Version
> 2017-05-03T20:14:53.9206240Z Description  : Updates the version of a CRM Solution
> 2017-05-03T20:14:53.9206240Z Version      : 8.2.0
> 2017-05-03T20:14:53.9206240Z Author       : Michaël Hompus
> 2017-05-03T20:14:53.9206240Z Help         : 
> 2017-05-03T20:14:53.9206240Z ==============================================================================
> 2017-05-03T20:14:55.8074152Z Updating Solution Version to **1.0.1$(Rev:.r)**
> 2017-05-03T20:15:10.1937098Z ##[error]The version is in an invalid format. Version: 1.0.1$(Rev:.r)
> 2017-05-03T20:15:10.2269142Z ##[section]Finishing: MSCRM Set Version: XXXXXXXXXXXXXXXXXXXX

Any ideas?

**Comment by eNeRGy164** [comment]
Are you running the task from build or release?

**Comment by namurdock** [comment]
Build, I use the exact same value for the build number within VSTS.

**Comment by eNeRGy164** [comment]
Ah, I messed up the documentation there. It seems you can't use $(rev) outside the build number format.
Because I always have another input for my version numbering so I didn't get caught by this.

For now, the quickest ways to get this working is
- Use another variable with a version number (without revision);
- Change the build number format to `1.0.1$(Rev:.r)`, and set the version number in the task to `$(Build.BuildNumber)`;

If you don't want the build number to only contain the version number we need some powershell magic.
1. Add a powershell script task with the following code befor the SetVersion task
```powershell
$newVersion = [version]($env:BUILD_BUILDNUMBER -replace ".*?(\d+)[._](\d+)[._](\d+)[._](\d+)", "`$1.`$2.`$3.`$4")
Write-Host "##vso[task.setvariable variable=GeneratedVersion;]$newVersion"
```
2. All tasks after this block will have access to the new variable $(GeneratedVersion).

This is a bit cumbersome. The task needs to be improved to handle this by default.

**Comment by namurdock** [comment]
Thanks, I think $(Build.BuildNumber); will do the trick for me.

It would be really good to see some articles  on putting everything together.

Starting from structuring projects in VS to build and release.

I have solutions unpacking and checking into source control but can't help feeling I am missing a trick.

Just an idea, thanks for the pointer.

**Comment by namurdock** [comment]
Thanks, I think $(Build.BuildNumber); will do the trick for me.

It would be really good to see some articles  on putting everything together.

Starting from structuring projects in VS to build and release.

I have solutions unpacking and checking into source control but can't help feeling I am missing a trick.

Just an idea, thanks for the pointer.

**Comment by WaelHamze** [comment]
Glad you got it working and thanks for your feedback. Yes more articles is certainly one of the things I intend to do.

**Comment by IvanKirianov** [comment]
Hi All,

I see that this problem is still present in VSTS extension. Do you have a plan to fix it out ? 

Thanks!

**Comment by WaelHamze** [comment]
@IvanKirianov What is the issue you are facing? are you not able to use the suggestion by @eNeRGy164

**Comment by bluonic** [comment]
Hi @eNeRGy164! I am running into the same issue above and neither the solution via $(Build.BuildNumber) nor the PS script helps. I can continue troubleshooting it myself but do you mind shedding some light on why the dynamic Build Number poses such challenge for the Set Version task?

For static definition, it works just fine:
```
Build Number: 1.0.0.7
Set Version (v12): $(Build.BuildNumber)
```

But when I change it to:
```
Build Number: 1.0.0$(Rev:.r)​
Set Version (v12): $(Build.BuildNumber)
```

It fails:
```
Updating solution version to 1.0.0.7
##[error]The version is in an invalid format. Version: 1.0.0.7
```

Even when I use your PS script, it fails because it cannot parse the version despite your attempt to reassemble it digit by digit:
```
Cannot convert value "1.0.0.7​" to type "System.Version".
Error: "Input string was not in a correct format."
At D:\a\_temp\848efa4b-7f4e-4df0-a419-a4e61ba8264c.ps1:5 char:1
+ $newVersion = [version]($env:BUILD_BUILDNUMBER -replace ".*?(\d+)[._] ...
```

In all instances the Build Number is in the correct format, it is interpreted as a string, but it can never be parsed. What am I missing? This used to work for me just fine.

Thanks a lot!

**Comment by bluonic** [comment]
Found the problem:

For some reason, $(Build.BuildNumber) variable **contains several non-printable characters** at the end which are not visible in the console:

`1.0.0.7â€‹`

I am not sure why @eNeRGy164's regex did not work for me but this did the trick:

```
## Remove all non-printable characters
$cleanVersion = [version]($env:BUILD_BUILDNUMBER -replace "[^ -~]")

##Save 
Write-Host "##vso[task.setvariable variable=cleanVersion;]$cleanVersion"
```

However, this means that the PowerShell task seems mandatory if you want to use $(Build.BuildNumber) as the solution version in SetVersion for now.

**Comment by WaelHamze** [comment]
@bluonic $(Build.BuildNumber) should work in the task. In fact I have used in the getting started video: https://youtu.be/rl62P68UxE4

**Comment by bluonic** [comment]
I used the task previously and it just worked. No idea why it doesn't work in that one DevOps environment. Hopefully nobody will have to use the trick above. Nice video!
