### ISSUE TITLE
Backup command is not working

### ISSUE THREAD

**Issue by saksingh** [WaelHamze/xrm-ci-framework#222]
1:MS CRM Backup online instance is not working..
Giving error at "Instance Name"
{already reffered to the format https://[instancename].crm[n].dynamics.com}
used the "instance name"  
"Instance not found errror"

2: Used powershell cmdlets for backups as well but requirement is until bakup not finished next task wont be executed but it is working asynchronously script get executed when backup still not created 

Any suggesstions

**Comment by WaelHamze** [comment]
@saksingh 

so if the url of your instance is https://instance1.crm11.dynamics.com

Then the instance name should be: instance1

The task has a wait in it until the backup is initiated, normally the backup will be based on the time you start the backup, so you should be able to carry on with next tasks. If you are ensure I would suggest you try the rollback and test to ensure you are getting the expected behaviour.
