### ISSUE TITLE
Licensing Costs

### ISSUE THREAD

**Issue by nimblejoe** [WaelHamze/xrm-ci-framework#32]
Hello,

The marketplace says that this toolkit is free during preview.  Do you have an estimate for what you will charge when the product is fully released?

Thanks,
Brian

**Comment by blastdan** [comment]
I'm actually interested in this as well

**Comment by eNeRGy164** [comment]
I think that's because of [this line in the manifest](https://github.com/WaelHamze/xrm-ci-framework/blob/master/CRM365/Xrm.Framework.CI/Xrm.Framework.CI.VSTS.BuildTasks/Extension/vss-extension.json#L17) stating it's `Preview` _and_ `Public`.
This is not a combination mentioned at the [Marketplace discovery properties](https://www.visualstudio.com/en-us/docs/integrate/extensions/develop/manifest#marketplace-discovery-properties). 

That page clearly states: 

> Only extensions marked as `paid preview` can be converted to `paid`.

So this solution can't be converted in a paid product.

Therefore I think this is just a display issue in the marketplace. Which could be resolved by removing the `Preview` flag, as it's public now anyway.

**Comment by WaelHamze** [comment]
Interesting questions. I have currently no plans of converting this framework into a paid version. The preview flag was mainly to indicate that this framework is new.
