### ISSUE TITLE
Issues with PowerShell and TF.exe

### ISSUE THREAD

**Issue by felipeblima** [WaelHamze/xrm-ci-framework#40]
Hello Wael.

First of all, congratulations for this - we started to use the framework here and it is very useful.

We are facing some issues with a script that perform some automations on TFS using tf.exe (extract customisations of CRM 2015).

Actually, the errors occur with the powershell variable $_files, which sometimes has multiple files and it seems that the powershell is sending the wrong format for the tf.exe (multiple files are interpreted as a single file, throwing an error of length exceed maximum of 259 characters). I'm not very familiar with powershell, and I'm thinking in rewrite the same logic on c#.

Have you ever experienced the same? If yes, any work around?

Thank you so much,
Felipe

**Comment by WaelHamze** [comment]
Hi Felipe,

I have not seen this error before. I have been using GIT version for some years now. It makes things a lot easier as it tracks the file system so all you have to do is just run the script and commit at the end and not worry about checkin/out. I recommend using it for managing solution files.

Regarding the script. Perhaps if you are deleting too many files the path may be too long. You could change the logic before to use a loop and delete/add one file at a time instead of doing them all in one go.

if ($deletedFiles.Length -gt 0)
{
    Write-Output "Deleted Files:" $deletedFiles
    
    $_files = [System.String]::Join(""" """, $deletedFiles)
    
    & "$tfCommand" undo /noprompt "$_files"
    & "$tfCommand" delete /noprompt "$_files"
}
if ($addedFiles.Length -gt 0)
{
    Write-Output "Added Files:" $addedFiles
    $_files = [System.String]::Join(""" """, $addedFiles)
    
    & "$tfCommand" add /noprompt "$_files"
}

**Comment by felipeblima** [comment]
Hi Wael,

Thanks for your response.

It is exactly what I did and it is working fine - just a little slower than before, but there is no other option.

Unfortunately, I don't have the option to use GIT.

Thanks,
Felipe
